<?php
/**
 * @file
 * Hides the comment subject if the "Allow custom title for comment" checkbox is
 * unchecked for that node type.
 */


/**
 * Implements hook_preprocess_HOOK() for a comment.
 */
function comment_hide_subject_preprocess_comment(&$variables) {
  $type = $variables['node']->type;
  $settings = config_get("node.type.{$type}", 'settings');
  $subject_enabled = $settings['comment_subject_field'];
  if (!$subject_enabled) {
    // The Drupal module set the title_attributes as in the commented out text,
    // but Backdrop themes don't support that. So instead, we'll just completely
    // wipe out the title.
//    $variables['title_attributes_array']['class'][] = 'element-invisible';
    $variables['title'] = '';
  }
}
